server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/transacao
    username: admin
    password: 123456
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql

  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true

  main:
    allow-bean-definition-overriding: true

app-config:
  nome: Guia Bolso - Transação API
  descricao: API REST do projeto Transação API para aplicação da vaga de Back-end Engineer no Guia Bolso
  versao: 1.0.0
  url: localhost:${server.port}